import type { Report } from "./types";

function escapeHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

/**
 * Builds a standalone HTML export of the visual direction report.
 * Self-contained — no external dependencies, inline CSS only.
 * Mirrors _build_report_html() from the original Streamlit app (ui/app.py).
 */
export function buildReportHtml(
  report: Report,
  keyword: string,
  langsmithUrl?: string | null,
  served?: string[]
): string {
  const kw = escapeHtml(keyword.toUpperCase());

  const paletteHtml = (report.palette ?? [])
    .map((sw) => {
      const hx = escapeHtml(sw.hex_code ?? "#CCC");
      const nm = escapeHtml((sw.name ?? "").slice(0, 16));
      return (
        `<div style="display:flex;flex-direction:column;align-items:center;">` +
        `<div style="width:56px;height:56px;border-radius:5px;background:${hx};` +
        `border:1px solid rgba(0,0,0,0.12);box-shadow:0 1px 3px rgba(0,0,0,0.08);"></div>` +
        `<div style="font-size:0.65rem;color:#5A5450;text-align:center;margin-top:4px;` +
        `font-family:monospace;">${hx}<br>${nm}</div></div>`
      );
    })
    .join("");

  const typo = report.typography;
  const typoHtml = typo
    ? `<p style="margin:0.2rem 0;color:#2A2520;">Display: ${escapeHtml(typo.display_typeface ?? "")}</p>` +
      `<p style="margin:0.2rem 0;color:#2A2520;">Body: ${escapeHtml(typo.body_typeface ?? "")}</p>` +
      `<p style="margin:0.2rem 0;color:#2A2520;">Tracking: ${escapeHtml(typo.display_tracking ?? "")}</p>`
    : "";

  const photoItems = (report.photography_direction ?? [])
    .map(
      (d, i) =>
        `<p style="margin:0.25rem 0;color:#2A2520;">${i + 1}. ${escapeHtml(d)}</p>`
    )
    .join("");

  const doItems = (report.do_rules ?? [])
    .map(
      (r) =>
        `<p style="margin:0.2rem 0;color:#2A2520;font-size:0.9rem;">&#10003; ${escapeHtml(r)}</p>`
    )
    .join("");
  const dontItems = (report.dont_rules ?? [])
    .map(
      (r) =>
        `<p style="margin:0.2rem 0;color:#2A2520;font-size:0.9rem;">&#10005; ${escapeHtml(r)}</p>`
    )
    .join("");

  const brandsHtml = (report.benchmark_brands ?? [])
    .map(
      (b) =>
        `<p style="font-weight:600;color:#1A1714;margin:0.5rem 0 0.1rem 0;">${escapeHtml(b.name)}</p>` +
        `<p style="font-size:0.88rem;color:#2A2520;margin:0 0 0.6rem 0;">${escapeHtml(b.reference_note)}</p>`
    )
    .join("");

  const conflicts = report.conflicts_resolved ?? "";
  const conflictsSection = conflicts
    ? `<h3 style="color:#1A1714;margin-top:2rem;">Conflicts Resolved</h3>` +
      `<p style="color:#2A2520;">${escapeHtml(conflicts)}</p>`
    : "";

  const servedLine =
    served && served.length
      ? `<br>Served by ${escapeHtml(served.join(", "))}`
      : "";
  const traceLink = langsmithUrl
    ? `&nbsp;&nbsp;|&nbsp;&nbsp;<a href="${escapeHtml(langsmithUrl)}" style="color:#6A6460;">LangSmith trace ↗</a>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Visual Direction — ${kw}</title>
<style>
  body { font-family: Georgia, serif; background: #F5F1ED; color: #2A2520;
          max-width: 820px; margin: 0 auto; padding: 3rem 2rem; }
  h1   { font-size: 2rem; letter-spacing: 0.08em; color: #1A1714; margin-bottom: 0.3rem; }
  h2   { font-size: 1.15rem; font-weight: 700; color: #1A1714; margin: 2rem 0 0.5rem 0;
          text-transform: uppercase; letter-spacing: 0.05em; }
  hr   { border: none; border-top: 1px solid #D5CFC8; margin: 1.5rem 0; }
  blockquote { border-left: 3px solid #A8B5A1; background: #EDE8E2; padding: 0.8rem 1rem;
                border-radius: 0 4px 4px 0; font-style: italic; margin: 0 0 1.5rem 0; }
  .swatch-row { display: flex; gap: 12px; flex-wrap: wrap; margin: 0.8rem 0 1.5rem 0; }
  .do-dont { display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; }
  .label { font-size: 0.7rem; letter-spacing: 0.12em; text-transform: uppercase;
             color: #6A6460; margin-bottom: 0.5rem; }
  footer { margin-top: 3rem; font-size: 0.75rem; color: #9A948C; text-align: center; }
</style>
</head>
<body>
  <h1>${kw}</h1>
  <p style="color:#6A6460;font-size:0.8rem;margin-bottom:2rem;">Visual Direction Report — Generated by Visual Direction Research Agent</p>

  <blockquote>${escapeHtml(report.positioning_statement ?? "")}</blockquote>
  <hr>

  <h2>Palette</h2>
  <div class="swatch-row">${paletteHtml}</div>
  <hr>

  <h2>Typography</h2>
  ${typoHtml}
  <hr>

  <h2>Spatial</h2>
  <p>${escapeHtml(report.layout_approach ?? "")}</p>
  <p style="color:#5A5450;font-size:0.88rem;">${escapeHtml(report.negative_space_rule ?? "")}</p>
  <hr>

  <h2>Photography</h2>
  ${photoItems}
  <hr>

  <h2>Do / Don't</h2>
  <div class="do-dont">
    <div><div class="label">Do</div>${doItems}</div>
    <div><div class="label">Don't</div>${dontItems}</div>
  </div>
  <hr>

  <h2>Benchmark Brands</h2>
  ${brandsHtml}
  <hr>

  <h2>Visual Narrative</h2>
  <p style="line-height:1.9;font-style:italic;">${escapeHtml(report.visual_narrative ?? "")}</p>

  ${conflictsSection}

  <footer>
    Visual Direction Research Agent &mdash; Capstone 2026
    ${traceLink}
    ${servedLine}
  </footer>
</body>
</html>`;
}

/** Triggers a browser download of the report as a standalone HTML file. */
export function downloadReportHtml(
  report: Report,
  keyword: string,
  langsmithUrl?: string | null,
  served?: string[]
): void {
  const html = buildReportHtml(report, keyword, langsmithUrl, served);
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `visual_direction_${keyword.replaceAll(" ", "_")}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
